runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'my-kart-admin'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'mykart'
  INSTANCE_CONNECTION_NAME: 'mykart-348523:us-central1:my-kart-admin'

beta_settings:
  cloud_sql_instances: 'mykart-348523:us-central1:my-kart-admin'